### PR TITLE
Portfolio: preserve data in the browser

### PR DESCRIPTION
**Pull request by osmanwako**
- When the user changes the content of three input fields, the data is saved to the local storage.
-  When the user loads the page, if there is any data in the local storage the input fields are pre-filled with this data.
-  All the above inputs have been  stored in a javascript object to retrieve and save  in local storage

### CODE REVIEW

**Comment by osmanwako** [comment]
Screenshot (142)
Screenshot (143)
Screenshot (144)
Screenshot (145)
Screenshot (146)

**Comment by osmanwako** [comment]
I appeal for transverse to next week

**Review by nahnahdev — COMMENTED** [review]
## Project Status: INVALIDATED :red_circle: 
Hi @osmanwako , 

While you made a great effort in this project, I can't go ahead and review your code.


## Invalid Code Review Request

- This is because you have submitted a project, that has already been merged into master and has a closed pull request :100: 
 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by osmanwako** [comment]
Sorry, my brother I completed every activity the previous time but due to an eslinter error related to an operating system issue one activity was left.  i appeal this issue to microverse kindly give me the above feedback. And also remove my code partner.
did you see may dashboard?

**Comment by nahnahdev** [comment]
Hello @osmanwako , Per the guidelines a merged pull request can't be approved  so I will suggest that you create a new pull request that contains the required changes and submit it :+1:

**Pull request merged**
