### PR TITLE
Portfolio: preserve data in the browser

### PR DESCRIPTION
**Pull request by osmanwako**
- When the user changes the content of three input fields, the data is saved to the local storage.
-  When the user loads the page, if there is any data in the local storage the input fields are pre-filled with this data.
-  All the above inputs have been  stored in a javascript object to retrieve and save  in local storage

### CODE REVIEW

**Comment by osmanwako** [comment]
Screenshot (142)
Screenshot (143)
Screenshot (144)
Screenshot (145)
Screenshot (146)

**Comment by osmanwako** [comment]
I have no code partner

**Review by didierganthier — CHANGES_REQUESTED** [review]
Hi @osmanwako ,

🎉 Good job so far! You're making great progress on this project, but there are still a few areas that need attention before we can move on to the next step.



## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct GitHub flow ✔️ 

## Required Changes 🛠
- [ ] Nice work on persisting the data 📦 but the `change` event is causing the data to not be saved while entered 🤔 it only gets saved when I go to the next input, in order to fix this you can replace the `change` event in these lines by `input` events. 👇🏽 
Screenshot 2023-03-13 at 21 15 03
- [ ] Two sections of your README 2️⃣ are currently empty 🗑️ the `Key Features` and the `Contributing`, make sure to add valuable info to them. ℹ️ 

- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

**Review by codepantha — APPROVED** [review]
# STATUS: APPROVED 🟢 ✔️ 

## Hi @osmanwako 👋, 

Well done for implementing the required changes 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
